# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c339d9b95496247253f183caaa830dd7"
name = "Smart Bundle App"
application_url = "https://shopify-bunddler-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_cart_transforms,read_cart_transforms,write_discounts,read_discounts"

[auth]
redirect_urls = [
  "https://shopify-bunddler-app.onrender.com/api/auth",
  "https://shopify-bunddler-app.onrender.com/auth/callback",
  "https://shopify-bunddler-app.onrender.com/auth/shopify/callback",
  "https://shopify-bunddler-app.onrender.com/api/auth/callback"
]
